development:
  adapter: postgresql
  database: saarchiver/development   # name this whatever you want
  host: localhost
  pool: 5          
  username: postgres
  password: password                  
  timeout: 5000                

production:
  adapter: postgresql
  database: saarchiver/development   # name this whatever you want
  host: localhost
  pool: 5          
  username: felipe
  password: password                  
  timeout: 5000                